[features]
seeds = false

[provider]
cluster = "localnet"
wallet = "/home/john/.config/solana/id.json"

[programs.localnet]
vesting_contract = "Btf6rov5qyFDkrarrHb9r4Dpi1ruBQMdUJBREdZXYpXi"
[programs.devnet]
vesting_contract = "Btf6rov5qyFDkrarrHb9r4Dpi1ruBQMdUJBREdZXYpXi"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
